name: hamsatech_design_system_example
description: Showcase app for HamsaTech Design System.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  hamsatech_design_system:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
